#ifndef MND_LWIPOPTS_H
#define MND_LWIPOPTS_H
#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_ICMP 1
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define MEM_ALIGNMENT 4
#define MEM_SIZE 32768
#define MEMP_NUM_TCP_SEG 128
#define MEMP_NUM_ARP_QUEUE 10
#define PBUF_POOL_SIZE 32
#define TCP_MSS 1460
#define TCP_WND (16*TCP_MSS)
#define TCP_SND_BUF (16*TCP_MSS)
#define TCP_SND_QUEUELEN 128
#define LWIP_TCP_KEEPALIVE 1
#define LWIP_CHKSUM_ALGORITHM 3
#define LWIP_STATS 0
#define DHCP_DOES_ARP_CHECK 0
#endif
