<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/MultiNodeDAQ.Protocol/MultiNodeDAQ.Protocol.csproj"/><ProjectReference Include="../../src/MultiNodeDAQ.Recording/MultiNodeDAQ.Recording.csproj"/></ItemGroup></Project>
