<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF></PropertyGroup><ItemGroup><ProjectReference Include="../../src/MultiNodeDAQ.Desktop/MultiNodeDAQ.Desktop.csproj"/><ProjectReference Include="../../src/MultiNodeDAQ.Simulator/MultiNodeDAQ.Simulator.csproj"/></ItemGroup></Project>
