<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup></PropertyGroup><ItemGroup><ProjectReference Include="../MultiNodeDAQ.Protocol/MultiNodeDAQ.Protocol.csproj" /><ProjectReference Include="../MultiNodeDAQ.Core/MultiNodeDAQ.Core.csproj" /><ProjectReference Include="../MultiNodeDAQ.Recording/MultiNodeDAQ.Recording.csproj" /></ItemGroup></Project>